// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchAndExport(arg1) {
  return window['go']['uiapi']['AggregationAPI']['SearchAndExport'](arg1);
}
