// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function List(arg1:dto.HistoryFilter):Promise<Array<dto.OrderRecord>>;

export function MarkTsdCreated(arg1:string,arg2:string):Promise<dto.OrderRecord>;
