// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function List(arg1) {
  return window['go']['uiapi']['HistoryAPI']['List'](arg1);
}

export function MarkTsdCreated(arg1, arg2) {
  return window['go']['uiapi']['HistoryAPI']['MarkTsdCreated'](arg1, arg2);
}
