// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Run(arg1) {
  return window['go']['uiapi']['IntroductionAPI']['Run'](arg1);
}
