// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CheckStatus(arg1:string):Promise<dto.OperationStatus>;

export function Create(arg1:Array<dto.OrderDraft>):Promise<Array<dto.OrderRecord>>;

export function Download(arg1:string):Promise<dto.DownloadArtifact>;
