// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckStatus(arg1) {
  return window['go']['uiapi']['OrdersAPI']['CheckStatus'](arg1);
}

export function Create(arg1) {
  return window['go']['uiapi']['OrdersAPI']['Create'](arg1);
}

export function Download(arg1) {
  return window['go']['uiapi']['OrdersAPI']['Download'](arg1);
}
